/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001b3d",
        "surface-bright": "#f6faff",
        "on-primary-fixed-variant": "#00468c",
        "background": "#f6faff",
        "primary-fixed": "#d6e3ff",
        "on-error": "#ffffff",
        "tertiary-container": "#c10023",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-primary": "#a9c7ff",
        "secondary-fixed": "#78fc9c",
        "on-secondary-container": "#007236",
        "surface-tint": "#005db6",
        "surface-variant": "#dbe4ed",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#5adf82",
        "on-tertiary-fixed-variant": "#930018",
        "on-secondary-fixed": "#00210b",
        "inverse-on-surface": "#e9f2fb",
        "on-surface": "#141d23",
        "on-tertiary-container": "#ffcecb",
        "on-secondary": "#ffffff",
        "tertiary": "#940018",
        "on-primary-container": "#c8daff",
        "primary-container": "#005eb8",
        "surface-container": "#e6eff8",
        "inverse-surface": "#293138",
        "on-background": "#141d23",
        "surface-container-low": "#ecf5fe",
        "error": "#ba1a1a",
        "surface-container-highest": "#dbe4ed",
        "tertiary-fixed": "#ffdad7",
        "secondary-container": "#75f999",
        "secondary": "#006d33",
        "outline": "#727783",
        "surface-container-high": "#e0e9f2",
        "on-surface-variant": "#424752",
        "on-error-container": "#93000a",
        "outline-variant": "#c2c6d4",
        "surface": "#f6faff",
        "tertiary-fixed-dim": "#ffb3af",
        "primary": "#00478d",
        "surface-dim": "#d2dbe4",
        "on-tertiary-fixed": "#410005",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#005225",
        "primary-fixed-dim": "#a9c7ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "container-max": "1280px",
        "gutter": "24px",
      },
      fontFamily: {
        'title-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}